spring:
  application:
    name: api

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

adote:
  security:
    secret: "hefwoaiuehfoiwahefoiauwhefiouawhefoaiuhwefhioaefwiouhaoi"
